FROM golang:1.23-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /trips.bin ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /trips.bin /app/trips.bin
RUN chmod 755 /app/trips.bin
ENTRYPOINT ["/app/trips.bin"]
