FROM golang:1.23-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /users.bin ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /users.bin /app/users.bin
RUN chmod 755 /app/users.bin
ENTRYPOINT ["/app/users.bin"]
