FROM golang:1.22-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /desktop.bin ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /desktop.bin /desktop.bin
RUN chmod 755 /desktop.bin
ENTRYPOINT ["/desktop.bin"]
