apiVersion: v1
name: trips
description: vtrips helm chart (renamed from backend)

version: 1.0.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
