FROM golang:1.23-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /trips.bin ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /trips.bin /trips.bin
RUN chmod 755 /trips.bin
ENTRYPOINT ["/trips.bin"]
