FROM golang:1.24-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /frontend.bin ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /frontend.bin /app/frontend.bin
RUN chmod 755 /app/frontend.bin
ENTRYPOINT ["/app/frontend.bin"]
